[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "scaffold"
# version = "0.0.1"
dynamic = ["version"]
authors = [
  { name="Dustin Lennon", email="dustin.lennon@gmail.com" },
]
description = "scaffold"
readme = "README.md"

# N.B., argparse introduced breaking changes affecting parse_known_args
#       [ref](https://github.com/omni-us/jsonargparse/pull/644)
requires-python = "==3.12.3"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: POSIX",
    "License :: OSI Approved :: MIT License",
]
dependencies = [
  "jinja2>=3.1.6",
  "pytz>=2025.1",
  "pyyaml>=6.0.2"
]

[project.urls]
Homepage  = "https://github.com/dustinlennon/scaffold"
Issues    = "https://github.com/dustinlennon/scaffold/issues"

[tool.setuptools]
include-package-data = true

[tool.setuptools.dynamic]
version = {file = "version"} 
dependencies = {file = "requirements.txt"}

# be explicit with find inclusions
# [tool.setuptools.packages.find]
# where = ["src/"]
# include = [
#   "scaffold.params*",
#   "scaffold.samples"
# ]

